---

- name: Install prerequsites
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - zip
    - unzip
    - acl
    - git

- name: Create folders
  file:
    state: directory
    owner: "{{ nextcloud_path_owner }}"
    group: "{{ nextcloud_path_group }}"
    path: "{{ item }}"
  with_items:
    - "{{ nextcloud_path }}"
