---
- name: Install prerequsites
  apt: pkg="{{ item }}" state=present update_cache=yes
  with_items:
    - zip
    - unzip
    - acl
    - git

- include: download.yml

- include: php.yml
  when: nextcloud_install_php

- include: database.yml
  when: nextcloud_install_database

- include: nginx.yml
  when: nextcloud_install_nginx

- include: install.yml
