---

- include_role: name=nbz4live.php-fpm private=true
  vars:
    php_fpm_version: "{{ nextcloud_php_version }}"
    php_fpm_apt_packages:
      - "php{{ nextcloud_php_version }}-fpm"
      - "php{{ nextcloud_php_version }}-pgsql"
      - "php{{ nextcloud_php_version }}-gd"
      - "php{{ nextcloud_php_version }}-xml"
      - "php{{ nextcloud_php_version }}-zip"
      - "php{{ nextcloud_php_version }}-curl"
      - "php{{ nextcloud_php_version }}-mbstring"
      - "php-apcu"
      - "php-apcu-bc"
    php_fpm_pools:
      - name: nextcloud
        user: "{{ nextcloud_websrv_user }}"
        group: "{{ nextcloud_websrv_user }}"
        listen: 9001
        chdir: /
