# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "nextcloud"
  config.vm.box = "plumelo/xenial64"

  config.vm.provider :lxc do |lxc, override|
    lxc.container_name = "nextcloud"
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'test.yml'
    ansible.galaxy_role_file='galaxy.yml'
  end
end
